title: Grist Wood
author: Michael Wiggins
email: info@gristwood.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Grist Wood, restoring ancient woodland in the High Weald of Sussex
theme: minima
# social links
github_username:  michaeljohnwiggins # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
